@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Schedule *-right-> "1" UniqueEventList
Schedule *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueEventList
UniqueTagList -[hidden]down- UniqueEventList

UniqueTagList *-right-> "*" Tag
UniqueEventList -right-> Event

Event -up-> "*" Tag

Event *--> Name
Event *--> Date
Event *--> Email
Event *--> Location
@enduml
