@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Schedule *-right-> "1" SortedEventList
Schedule *-right-> "1" UniqueTagList
Schedule *--> "1" SortedBlockedSlotList
UniqueTagList -[hidden]down- SortedEventList
UniqueTagList -[hidden]down- SortedEventList
SortedBlockedSlotList -down-> BlockedSlot
BlockedSlot -down-> Date
BlockedSlot -down-> TimeSlot


UniqueTagList *-down-> "*" Tag
SortedEventList -right-> Event

Event -up-> "*" Tag

Event *--> Name
Event *--> Date
Event *--> TimeSlot
Event *--> Location

TimeSlot -[hidden]right-> Date
TimeSlot -[hidden]right-> Name
Name -[hidden]right-> Location
Location -[hidden]right-> Tag
@enduml
