@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ScheduleParser" as ScheduleParser LOGIC_COLOR
participant ":FilterByTagCommandParser" as FilterByTagCommandParser LOGIC_COLOR
participant "f:FilterByTagCommand" as FilterByTagCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("filter_tag URGENT")
activate LogicManager

LogicManager -> ScheduleParser : parseCommand("filter_tag URGENT")
activate ScheduleParser

create FilterByTagCommandParser
ScheduleParser -> FilterByTagCommandParser
activate FilterByTagCommandParser

FilterByTagCommandParser --> ScheduleParser
deactivate FilterByTagCommandParser

ScheduleParser -> FilterByTagCommandParser : parse("URGENT")
activate FilterByTagCommandParser

create FilterByTagCommand
FilterByTagCommandParser -> FilterByTagCommand
activate FilterByTagCommand

FilterByTagCommand --> FilterByTagCommandParser : f
deactivate FilterByTagCommand

FilterByTagCommandParser --> ScheduleParser : f
deactivate FilterByTagCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FilterByTagCommandParser -[hidden]-> ScheduleParser

ScheduleParser --> LogicManager : f
deactivate ScheduleParser

LogicManager -> FilterByTagCommand : execute(model)
activate FilterByTagCommand

FilterByTagCommand -> Model : updateFilteredEventList(predicate)
activate Model

Model --> FilterByTagCommand
deactivate Model

create CommandResult
FilterByTagCommand -> CommandResult
activate CommandResult

CommandResult --> FilterByTagCommand : result
deactivate CommandResult

FilterByTagCommand --> LogicManager : result
deactivate FilterByTagCommand
destroy FilterByTagCommand

[<--LogicManager
deactivate LogicManager
@enduml
