@startuml
'https://plantuml.com/activity-diagram-beta
!include style.puml
start
:merge SortedEventList and SortedBlockedSlotList;
:construct list to store freeSlots;
if(no Overlappable in schedule) then (yes)
    :return empty list of freeSlots;
    stop
else (no)
    :add freeSlot from 0000 today to\nstart time of first Overlappable;
    repeat
    :get previous Overlappable;
    :get current Overlappable;
    :add freeSlot in between previous\nand current Overlappable;
    repeat while(last Overlappable?) is (no)
    ->yes;
    :add freeSlot from end time of last Overlappable\nto 2359;
    :remove all past freeSlots;
    :return list of freeSlots;
    stop
@enduml
