@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlySchedule <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Interface Overlappable <<Interface>>
Interface SortedOverlappableList <<Interface>>
Class Schedule
Class ReadOnlySchedule
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Class SortedBlockedSlotList
Class BlockedSlot

Class SortedEventList
Class Event
Class Location
Class TimeSlot
Class Name
Class Date
Class Tag

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Schedule .up.|> ReadOnlySchedule

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlySchedule
ModelManager -left-> "1" Schedule
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Schedule *--> "1" SortedEventList
SortedEventList --> "~* all" Event
Event *--> Name
Event *--> Date
Event *--> TimeSlot
Event *--> Location
Event *--> "*" Tag

Schedule *--> "1" SortedBlockedSlotList
BlockedSlot *--> Date
BlockedSlot *--> TimeSlot

Event .up.|> Overlappable
BlockedSlot .up.|> Overlappable

SortedEventList .up.|> SortedOverlappableList
SortedBlockedSlotList .up.|> SortedOverlappableList


Name -[hidden]right-> Date
Date -[hidden]right-> Location
Location -[hidden]right-> TimeSlot

ModelManager -->"~* filtered" Event
@enduml
