@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlySchedule <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class Schedule
Class ReadOnlySchedule
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniqueEventList
Class Event
Class Location
Class Time
Class Name
Class Date
Class Tag

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Schedule .up.|> ReadOnlySchedule

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlySchedule
ModelManager -left-> "1" Schedule
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Schedule *--> "1" UniqueEventList
UniqueEventList --> "~* all" Event
Event *--> Name
Event *--> Date
Event *--> Time
Event *--> Location
Event *--> "*" Tag

Name -[hidden]right-> Date
Date -[hidden]right-> Location
Location -[hidden]right-> Time

ModelManager -->"~* filtered" Event
@enduml
