@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "Schedule Storage" #F4F6F6{
Interface ScheduleStorage <<Interface>>
Class JsonScheduleStorage
Class JsonSerializableSchedule
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" ScheduleStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ScheduleStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonScheduleStorage .up.|> ScheduleStorage
JsonScheduleStorage ..> JsonSerializableSchedule
JsonSerializableSchedule --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
