@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ScheduleParser" as ScheduleParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedSchedule" as VersionedSchedule MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> ScheduleParser : parseCommand(undo)
activate ScheduleParser

create UndoCommand
ScheduleParser -> UndoCommand
activate UndoCommand

UndoCommand --> ScheduleParser
deactivate UndoCommand

ScheduleParser --> LogicManager : u
deactivate ScheduleParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoSchedule()
activate Model

Model -> VersionedSchedule : undo()
activate VersionedSchedule

VersionedSchedule -> VersionedSchedule :resetData(ReadOnlySchedule)
VersionedSchedule --> Model :
deactivate VersionedSchedule

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
